### ISSUE TITLE
Response Format 변경이 필요성 검토

### ISSUE THREAD

**Issue by NESOY** [snack-news/Snack-BE#10]
## Reference
- [ResponseEntity](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/ResponseEntity.html)

**Comment by NESOY** [comment]
## Response
- HttpStatus -> 기존 HttpStatus 이용
- OriginData -> Wrapping 하지 않고 바로 원본 데이터 제공
- Message -> Wrapping 하지 않고 바로 원본 데이터 제공

**Comment by Delf-Lee** [comment]
기존 컨트롤러에서 DTO를 반환하는 코드에서 HttpStatus를 커스텀하는게 가능할지 모르겠네요.

### Reference
- https://www.baeldung.com/spring-mvc-controller-custom-http-status-code
- https://cheese10yun.github.io/spring-guide-exception/

**Comment by Delf-Lee** [comment]
본 이슈를 닫고, #56 에 이어서 관리합니다.
