### ISSUE TITLE
어드민의  News List 정렬

### ISSUE THREAD

**Issue by MartinYounghoonKim** [snack-news/Snack-BE#109]
## 버그를 재현하려면 어떻게 해야 하나요? 🧐
- 어드민의 "News" 페이지를 진입하면 확인 가능합니다.

## 이 버그는 이렇게 잡으면 좋을거 같네요 🍺
- 지금 현재 sorting 기준이 index로 되어져 있는 것 같은데, 정렬순이 역순이 되어야할 것 같습니다.

## Reference
-

**Comment by Delf-Lee** [comment]
@NESOY 
여러모로 생각하다가 테스트가 불가능하다는걸 깨닫게 되었습니다.
어찌됐든 정렬을 처리하는 로직은 쿼리에서 하는거고 service에서 잡힌 mock으로는 그 로직을 검증할 수 없을 것 같네요...

저번에 말했던 것 처럼 굳이 테스트를 한다면 repository 단으로 내려야할 것 같습니다.

**Comment by NESOY** [comment]
@Delf-Lee 
네네 mock 처리해서 테스트하는건 힘들어보입니다 ㅠㅠ
repository level에서 테스트 하는 걸로 가시죠!
