### ISSUE TITLE
picks API

### ISSUE THREAD

**Issue by Delf-Lee** [snack-news/Snack-BE#152]
picks 기능 관련 API 추가
- picks 도메인 작성
- CRUD API 추가
- 테스트 작성 병행

**Comment by Delf-Lee** [comment]
관련 스펙 명시
https://opensourcekr.slack.com/archives/GP7FNTCGJ/p1578444290058800

## 정의
- Picks의 각 링크에 해당하는 하나의 요소를 pick(임시)이라고 칭한다.
- News의 각 뉴스에 해당하는 하나의 요소를 article(임시)라고 칭한다.

## 어드민 구성
### picks 리스트 view
- 기존 article view와 동일하게 구현

### picks 생성 view
필수 구성항목
- 카테고리(기존 카테고리와 동일)
- 토픽(기존 토픽과 동일 - 주로 회사)
- 링크
- 업로드 날짜

## 웹 UI 구성(picks 탭)
- pick UI에서는 링크만 보인다.(썸네일, 제목, 링크)
- 분류 정책 아직 없음
- 업로드 날짜 순으로 정렬

### 특정 회사 모아보기 UI
- picks탭을 신설한다. (토픽 별로 picks, article을 동시에 볼 수 있다)
- 분류는 picks탭과 동일하게 가져간다.

**Comment by Delf-Lee** [comment]
특정 회사 모아보기 기능에서 pick과 article을 동시에 보여주어야한다.

pick와 article을 공통 기능
- 시간 기준으로 정렬할 수 있다
- 카테고리 기준으로 정렬이 가능하다
- 토픽 기준으로 정렬이  가능하다(미정)

차이점은 보여지는 요소가 다르다는 것
- pick: 링크(링크 타이틀, 섬네일)
- article: 제목, 내용, 링크(링크 타이틀)

**Comment by NESOY** [comment]
@Delf-Lee 
추상클래스 Post로 접근하신 이유가 궁금하네요 :)
+ 추가적으로 JPA 조인 관련 내용은 오프라인으로 설명해주시면 감사하겠습니다. 👍

**Comment by Delf-Lee** [comment]
@NESOY 
- 기능적으로 picks와 article을 모두 보여줘야하는 요구사항이 있기 때문
- 구조적으로 두 요소 사이에 공통된 책임이 있기 때문

데이터베이스에선 상속이라는 구조가 없기때문에 이를 구현하기 위한 방법이 여러가지가 있더군요... 자세한 이야기는 오프라인에서 :smile:

**Comment by Delf-Lee** [comment]
@NESOY 
picks와 news 사이에는 공통사항이 존재하지만, 영재님은 그 공통사항이 "변경될 여지가 많다"라고 판단. 이는 앞으로 유지보수하는데에 비용이 더 들것이라 예상하고 두개의 요소를 별개의 클래스와 테이블로 관리하는게 낫다고 생각하시는거죠?

**Comment by NESOY** [comment]
@Delf-Lee 넹넹
