### ISSUE TITLE
데이터베이스에 의존적인 테스트 코드 변경(개선)

### ISSUE THREAD

**Issue by Delf-Lee** [snack-news/Snack-BE#42]
`"추가"를 검증하는 부분에서 "조회"로직까지 포함되는게 맞는건가요? 한 서비스 레이어의 기능을 검증하는데 있어 다른 서비스 레이어 로직이 끼어들 여지가 있어서 레파지토리에서 직접 조회하는 방법을 택했습니다.`
-> 추가 / 조회가 하나의 서비스라면 포함되는게 맞다고 봅니다.
만약 추가적으로 검증해야될 레파지토리가 많아지면.. 해당 서비스 레이어를 추가하는 방향이 더 좋지 않을까요?

`혹시 DB를 고려하지 않고 테스트 코드를 검증할 수 있나요?`
-> DB를 고려하지 않고 Mock처리해서 테스트를 검증할 수는 있습니다.

_Originally posted by @NESOY in https://github.com/snack-news/Snack-BE/pull/40_

**Comment by Delf-Lee** [comment]
테스트를 어떻게 개선할까 고민
## 현재 상태
- 단위 테스트의 필요성을 느낌
   - 각기 다른 테스트에서 같은 로직(코드)을 중복적으로 검증(호출)
   - 이로 인한 테스트 속도 및 효율성 저하
   - DB에 의존적, 또는 각 테스트 코드가 다른 테스트 코드에 의존적인 상태

## 개선안 제안
1. Repository 레이어 테스트는 메모리 DB와 연결하여 테스트
   - 이것도 완전 독립시키려면 따로 DB역할을 하는 클래스를 작성해야할 듯.
2. Service 레이어 테스트는 mock을 이용하여 DB(repository 레이어)와 독립적인 단위 테스트 구현
   - **DB와 독립적이라 함은 값이 정확한지 검증하지 않는다는 것.**
   - 어처피 여기서 검증하는 값은 우리가 mock을 통해 주입한 값.
3. Controller 레이어 테스트도 mock을 이용하여 DB와 독립적인 단위 테스트 구현.
   - **DB와 독립적이라 함은, response의 body 값을 검증하지 않는다는 것.**
4. 통합테스트 구현 Controller-Service-Repository-DB에 아우르는 테스트 구현

주요 의문은 볼드체로 적어둔 것으로 "과연 이런 검증에 구멍은 없는가" 라는 것.
그런 점을 통합테스트로 커버할 수 있지 않을까라는게 현재의 생각.

**Comment by Delf-Lee** [comment]
@NESOY 
테스트를 어떻게 개선할까 고민

## 현재 상태
- 단위 테스트의 필요성을 느낌
   - 각기 다른 테스트에서 같은 로직(코드)을 중복적으로 검증(호출)
   - 이로 인한 테스트 속도 및 효율성 저하
   - DB에 의존적, 또는 각 테스트 코드가 다른 테스트 코드에 의존적인 상태

## 개선안 제안
1. Repository 레이어 테스트는 메모리 DB와 연결하여 테스트
   - 이것도 완전 독립시키려면 따로 DB역할을 하는 클래스를 작성해야할 듯.
2. Service 레이어 테스트는 mock을 이용하여 DB(repository 레이어)와 독립적인 단위 테스트 구현
   - **DB와 독립적이라 함은 값이 정확한지 검증하지 않는다는 것.**
   - 어처피 여기서 검증하는 값은 우리가 mock을 통해 주입한 값.
3. Controller 레이어 테스트도 mock을 이용하여 DB와 독립적인 단위 테스트 구현.
   - **DB와 독립적이라 함은, response의 body 값을 검증하지 않는다는 것.**
   - 임의의 상황에서 원하는 상태(httpstatus)또는 예외 메시지를 내려주는가를 검증
4. 통합테스트 구현 Controller-Service-Repository-DB에 아우르는 테스트 구현

주요 의문은 볼드체로 적어둔 것으로 "과연 이런 검증에 구멍은 없는가" 라는 것.
그런 점을 통합테스트로 커버할 수 있지 않을까라는게 현재의 생각.

**Comment by NESOY** [comment]
무엇을 검증할것인가에 대한 초점을 생각해보면 좋을거같아요.
Service 레이어에서는 정확한 데이터를 가지고 `비즈니스 로직을 검증하는 것`이 가장 초점이 맞춰진다고 생각해요. 정확한 데이터가 있다는 전제로 DB를 Mocking을 함으로써 우리는 비즈니스 로직에만 신경쓰게 되는거 같아요.

구멍이 없는가.. 모든 구멍을 생각하면 힘이듭니다 ㅠㅠ..
테스트를 많이 짜는것도 중요하지만.. 우리의 비즈니스에 치명적인 부분을 위주로 테스트를 채워나가는게 좋지 않을까요?

**Comment by NESOY** [comment]
주제 자체가 추상적인 이슈로 조금 더 상세한 내용을 바탕으로 논의하기로 결정
해당 이슈 종료처리
