### ISSUE TITLE
API 컨벤션 협의

### ISSUE THREAD

**Issue by MartinYounghoonKim** [snack-news/Snack-BE#56]
일전 회의 때 API 컨벤션에 대해서 다같이 협의하고자 ISSUE 하나 생성합니다.
각각의 상태코드(status) 코드는 response 자체에 포함하며, 아래와 같은 데이터 구조를 가지면 어떨까하여 제안드립니다.

API 성공시, status 200과 아래와 같은 데이터 구조를 가집니다. 성공 시 에는 데이터를 제외하고는 별도의 response는 필요없을 것 같습니다. 

```json
{
  "data": [
    { ... }
  ]    
}
```

실패 시, status 400 혹은 500 와 함께 다음과 같은 데이터 구조를 가집니다. 실패 시에는 실패에 해당하는 메세지와 함께 별도의 ExceptionCode 정보가 있으면 좋을 것 같습니다.

```json
{
  "exceptionCode": "NULL POINT EXCEPTION",
  "exceptionMessage": "NPE 에러가 발생했습니다."
}
```

**Comment by Delf-Lee** [comment]
확인했습니다. #10 이슈에 이어서 관리하겠습니다.

**Comment by Delf-Lee** [comment]
@MartinYounghoonKim @vomvoru 
요청 값은 잘 받았고 잘 처리했지만, 값이 없는 경우는 statuscode 204에 빈 페이로드를 보내려고 하는데 괜찮을까요?
예를들어 2020년 12월 이후에 작성된 뉴스를 조회하는 경우겠네요.

달라지는게 있다면 기존의 포맷과 달리 아예 빈 body가 가는것이겠네요.
``` json
{
  "data": [
    { ... }
  ]    
}
```
참고 - https://github.com/snack-news/Snack-BE/pull/55#discussion_r307556059

### Reference
- https://medium.com/@laeshiny/get-요청-시-데이터가-없으면-200-or-404-4ab7430084af
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204

**Comment by Delf-Lee** [comment]
@MartinYounghoonKim @vomvoru @NESOY 
# 응답에 대하여
현재 예외 발생 시 보내는 응답에 포함되는 `exceptionCode`, `exceptionMessage`는 임의로 분류하고 작성하고 있습니다만, 혹시 분류에 고려해야할 요소가 있다면 알려주세요.

현재 예외가 발생할 대략적인 상황은 다음과 같습니다.

https://github.com/snack-news/Snack-BE/issues/58#issuecomment-515654030

**Comment by chul-hyun** [comment]
저는 좋다고 생각해요. 더 자세한 이유와 내용을 아래에 적자면..

204로 내려주는 형태에 대해서,
지금 그리고 추후 개발을 진행할때 좀 더 편리하게 디버깅을 진행할수 있을것 같아서 좋은것 같습니다.
추가로 우선순위는 낮춰서 진행해도 괜찮을것 같습니다.

@MartinYounghoonKim Client에서는 2xx 일때가 아니라 정확히 200일때 나머지 로직을 진행하도록 유의해서 작성해야 될것 같습니다. (가끔 라이브러리중 2xx 를 성공으로 보고 처리하는 경우가 있어서..)

**Comment by MartinYounghoonKim** [comment]
@vomvoru 
동의합니다.

@Delf-Lee 
그렇다면 GET에 대한 성공은 200이 되고 POST에 대한 성공은 201이 되는 방식처럼 세부적으로 분리를 해야하나요 ?

**Comment by Delf-Lee** [comment]
> @Delf-Lee
> 그렇다면 GET에 대한 성공은 200이 되고 POST에 대한 성공은 201이 되는 방식처럼 세부적으로 분리를 해야하나요 ?

@MartinYounghoonKim @vomvoru 
현재는 디폴트로는 둘다 200 상태코드를 반환합니다만, 응답 형식의 변경으로 인해 상태코드를 자유롭게 커스텀할 수 있게되었습니다.

두 상황에서 처리할게 다르다면 200과 201로 따로 보내드릴 수 있긴한데, 그렇게 진행할까요?

**Comment by NESOY** [comment]
FE 연동이 되었으므로 이슈 종료합니다 👍
