### ISSUE TITLE
예외처리 세분화 및 구체화

### ISSUE THREAD

**Issue by Delf-Lee** [snack-news/Snack-BE#58]
Response 형식에 관련되서 예외 상황에 대한 처리를 세분화 및 구체화 해서 그에 따른 알맞은 응답을 내려줄 필요가 있을 듯 합니다.

관련이슈: #56

**Comment by Delf-Lee** [comment]
@NESOY 
https://github.com/snack-news/Snack-BE/blob/master/src/main/java/com/snack/news/exception/base/NotFoundException.java#L6

혹시 이 어노테이션은 어떤 기능을 하는지 알 수 있을까요?

이제 DTO나 Entity 객체가 아닌 ResponseEntity 객체를 내려줌으로써 변경될 수 있는 부분 같아서요.

**Comment by Delf-Lee** [comment]
## News API
### 생성
- `POST: /api/news/`
   - 필수 인자가 포함되지 않았다. (title, content, categoryId) [구현]
   - 중복된 뉴스 title이 존재한다. [미구현]

### 조회
- `GET: /api/news`
   - 필터링할 조건이 없다. 즉, DB에 있는 뉴스 전체를 조회하려 한다. [미구현]
- `GET: /api/news/{id}`
   - 요청한 id에 해당하는 뉴스가 없다. [구현]

## Topic API
### 생성
- `POST: /api/topic/`
   - 필수 인자가 포함되지 않았다. (name) [구현]
   - 중복된 토픽 name이 존재한다. [미구현]

### 조회
- `GET /api/topic/{type}?sort={ordering}`
   - 부적절한 인자를 받았다. (type, ordering) [구현]

## Category API
### 생성
- `POST: /api/category`
   - 필수 인자가 포함되지 않았다. (title) [구현]
   - 중복된 카테고리 title이 존재한다. [미구현]

## Tag API
### 생성
- `POST: /api/tag`
   - 필수 인자가 포함되지 않았다. (title) [구현]
   - 중복된 태그 title이 존재한다. [미구현]

**Comment by NESOY** [comment]
@Delf-Lee 
예전에는 예외를 바로 던졌는데 ResposeEntity 사용하면 불필요한 부분같습니다.

**Comment by Delf-Lee** [comment]
### Reference
- Spring에서 @ControllerAdvice를 활용한 Exception 처리
   - https://www.slipp.net/questions/600
- wiki
   - https://docs.spring.io/spring/docs/4.3.12.RELEASE/spring-framework-reference/htmlsingle/#mvc-ann-exceptionhandler

@NESOY
