### ISSUE TITLE
News 리스트 조회 API 메소드 수정 건의

### ISSUE THREAD

**Issue by chul-hyun** [snack-news/Snack-BE#66]
현재 스펙은 아래와 같은데,

조건에 맞는 News 리스트 조회
/api/news (POST)

{
    "startDateTime" : "2019-07-01T00:00",
    "endDateTime" : "2019-08-31T00:00",
    "categoryId" : 1,
    "topicIds" : [1, 2],
    "tagIds" : [1]
}

혹시 POST 를 GET 메소드 형태로 바꾸는것에 대해 어떻게 생각하시나요?

@NESOY  @Delf-Lee

**Comment by Delf-Lee** [comment]
이전에도 POST메서드로 요청하시고, 이번에도 관련 건의를 주셔서 이상하다고 생각했더니
제가 readme의 api 안내 기재에 실수가 있었군요... 죄송합니다.

원래 GET 메서드 형태였고, 스펙 문서 표기가 잘못됐었습니다.

**Comment by chul-hyun** [comment]
앗, 그러고보니 저번에 그렇게 알려주신것 같은데 저야말로 실수했네요 ㅠㅠ 죄송합니다

어쨋든,
GET으로 body에 파라미터를 넣으려 하는데 계속 실패하네요.. 우선 계속 시도해보고 도움이 필요하면 요청하도록 하겠습니다.

**Comment by chul-hyun** [comment]
ajax 요청시 이슈가 있어서 다시 열었습니다.

https://xhr.spec.whatwg.org/#the-send()-method

본 문서를 봐보면 GET, HEAD 메소드로 보낼시 body 는 무시되고 전송됩니다 ㅠㅠ
즉, XHR(브라우저 ajax 요청 객체) 스펙이 HTTP 스펙을 따라가질 못하네용..

url 파라미터로 받을수 있게 스펙 수정 부탁드려요!

**Comment by NESOY** [comment]
@vomvoru

기존 HTTP Method는 유지하고
Body대신 Query String으로 파라미터를 받는 형식으로 진행하게 되었습니다.

cc @Delf-Lee

**Comment by Delf-Lee** [comment]
수정 완료됐습니다!

요청 예)
http://{host}:{port}/api/news?startDateTime=2019-07-01T00:00&endDateTime=2019-08-31T00:00&categoryId=1&topicIds=1,2&tagIds=1

**Comment by chul-hyun** [comment]
넵 감사합니다!!
XHR 스펙이 참 아쉽네요 ㅠㅠ

이슈는 닫도록 하겠습니다.

**Comment by Delf-Lee** [comment]
#56
