### ISSUE TITLE
static method mocking

### ISSUE THREAD

**Issue by Delf-Lee** [snack-news/Snack-BE#78]
## 왜 해당 이슈가 개선되어야 할까요? 🧐
- 날짜 검증을 담당하는 `WeekUtil` 클래스의 static method를 mock할 수 가 없어서 컨트롤러의 테스트가 실패하는 현상이 발생
- PowerMock을 사용하면 가능할 것으로 예상

## Reference
- https://stackoverflow.com/questions/21105403/mocking-static-methods-with-mockito/21116014#21116014
- https://www.journaldev.com/21912/mockito-mock-static-method-powermock#junit-mockito-powermock-example

**Comment by NESOY** [comment]
Powermock은 최대한 사용안하는방향으로 가시는건 어떨까요? 뭔가 다 넘어다니는 라이브러리라서 ㅠ

**Comment by Delf-Lee** [comment]
@NESOY 
'다 넘어다닌다'라는 점이 어떤 부분에서는 그리 좋지 않는 관점이라는 것은 인정합니다만, 실 서비스가 아닌 테스트 코드를 돌릴 때 사용하는거라는 점, 더 조사해보겠지만 static method를 검증하는 다른 방법이 보이지 않는다는 점에서 사용이 불가피하지 않을까 하고 예상합니다.

로직 자체를 바꾸거나(static method를 사용하지 않는 방향으로) 해당 메서드만 포함하지 않고 같은 작업을 하는 테스트용 API를 따로 작성하는 방법도 있겠네요.

일단 회의 전까지 조금 더 조사해보도록 하겠습니다. 추가로 테스트를 돌릴 때 이것저것 넘어다니는 것에 대한 부작용에 대해서 간단한 설명이나 레퍼런스를 달아주시면 감사하겠습니다 :smile:

**Comment by NESOY** [comment]
@Delf-Lee 
다시 생각을 정리하다보니까.. 굳이 `static method`를 Mocking할 필요성이 있을까?라는 궁금증이 생기네요.
Mocking하는 이유가 외부의 의존도를 낮추기 위해 하는거라고 생각하지만.. 
`WeekUtil`같은 경우에는 Util로 사용하는 클래스라서 굳이 Mocking이 필요할까? 라는 생각이 들었습니다.

의견 부탁드립니다 🙌

**Comment by Delf-Lee** [comment]
**굳이** 라는 표현은 이 경우 말고도 여기저기에 쓰일 수 있을 것 같네요. 희생하는 것에 대한 불편함을 남아있지만, 현 상황에 있어서 꺼림직한 방법을 쓰지 않고 가장 쉽게 넘어가는 방법이라는데에는 동의합니다.

- 얻을 수 있는 것
   - 꺼림직한 방법을 쓰지 않는다
   - 비지니스 로직을 건들지않고 간단하게 구현이 가능하다
- 희생해야하는 것
   - `WeekUtill` 에 종속적이고 다소 지저분해진 테스트 코드

제가 영재님 의견에 동의할 수 있는 이유는 **굳이** 라고 표현한 부분과 일맥상통합니다. 지금으로썬 `WeekUtil`가 변경될 여지가 불투명하긴 합니다. 하지만 일주일의 시작 요일이 변경되거나 다른 조건이 추가되는 등의 변화가 발생한다면 이에 대한 테스트 코드는 모두 변경되어야할 것입니다. 그리고 이것 역시 아직까지는 '감수할 수 있는 부분' 내인것 같네요.

**Comment by Delf-Lee** [comment]
해당 로직은 유틸의 범주에 포함되지 않는다고 판단하여, 검증을 비지니스 안에 녹이고 static method를 테스트할 필요가 없도록 변경
